### ISSUE TITLE
Insert page # in footer

### ISSUE THREAD

**Issue by daniel-buona** [joseluisq/printd#13]
## Expected Behavior
Hi!
Is there a way to automatically include a page counter in the footer of all pages?

## Specifications
  - Browser version: `IE, Chrome and Firefox`

**Comment by joseluisq** [comment]
Can you explain me a bit more in detail what do you want to do?

**Comment by daniel-buona** [comment]
If you see in the attached image, I would like to do something like point 1, without having to use point 2
![Capturar](https://user-images.githubusercontent.com/52827800/82946086-22f92f00-9f74-11ea-9a81-0c5e605ec9f7.PNG)

**Comment by joseluisq** [comment]
I understand.
Unfortunately this library is not intended to have built-in support for such HTML elements because it doesn't provide any GUI. 
So your components could be a developer task and they are out of this library's scope.

Here a description about the scope of this library:

> Printd opens your Browser Print Dialog to print HTML elements inside a blank document or pages by URL.

You can take a look at project's `README.md` file or the [source](https://github.com/joseluisq/printd/blob/master/src/index.ts) file for more details.

I'm going to close this issue. Feel free to reopen it if needed.

**Comment by daniel-buona** [comment]
Tks man!
