### ISSUE TITLE
Print selected value in select tag html

### ISSUE THREAD

**Issue by JoaquinSerrano** [joseluisq/printd#14]
## Expected Behavior

A selected option of select html tag should be printed

## Actual Behavior
By default, the printed version is showing the first option of select tag and not the selected option.

## Steps to Reproduce the Problem

  1. Insert a select tag with multiple options
  1. Select the second, thirth, fourth... option, what you prefer
  1. When you print the page always the first option is showed

## Workaround

...

## Specifications

  - Version: `v1.4.1`
  - Platform: `v0.0.0`
  - Node version: `v10.15.3`
  - Browser version: `Chrome Versión 83.0.4103.61`

## Web Version
<img width="309" alt="Captura de pantalla 2020-05-28 a las 9 36 46" src="https://user-images.githubusercontent.com/29888531/83112651-c9ede000-a0c6-11ea-9422-cb43b2a93ef4.png">

## Printed Version
<img width="262" alt="Captura de pantalla 2020-05-28 a las 9 37 57" src="https://user-images.githubusercontent.com/29888531/83112784-f30e7080-a0c6-11ea-8b93-9cc17f4401a5.png">

**Comment by joseluisq** [comment]
Selected options on `select` HTML elements only work for `option` elements with the static `selected` attribute but not dynamic ones. You can take a look at https://codepen.io/joseluisq/pen/VzRpGb which is using `v1.4.2`.

You can solve it updating your dynamic selected option with the `selected` attribute too.
Additionally here you have another workaround https://css-tricks.com/making-selects-printable/

I'm going to close this issue since it is not related to Printd.

**Comment by JoaquinSerrano** [comment]
Muchas gracias Jose Luis
