### ISSUE TITLE
Printd event `afterprint` not work on Chrome

### ISSUE THREAD

**Issue by roeurbnavy** [joseluisq/printd#21]
## Specifications
  - Version: `1.51`
  - Browser version: `109.0.5414.87`
 
## Steps will reproduce the problem.
(1) Press 'print button'
(2) Cancel print modal
 
## My code 
```js
  mounted() {
    // Printd
    this.d = new Printd()
  },
  methods: {
    print() {
      const callback = ({ launchPrint }) => {
        launchPrint()
      }

      this.d.print(document.getElementById('printing'), [], [], callback)

      // then add your event handlers
      const { contentWindow } = this.d.getIFrame()
      if (contentWindow) {
        contentWindow.addEventListener('beforeprint', () => {
          console.log('before print event!')
        })
        contentWindow.addEventListener('afterprint', () => {
          console.log('after print event!')
        })
      }
    },
  },
```
 
https://user-images.githubusercontent.com/20157836/212275985-cc70cb40-6094-404e-926e-1764d8cc8e10.mov

**Comment by joseluisq** [comment]
Just move your browser print events after calling `d.print()`. See https://codepen.io/joseluisq/pen/VzRpGb (updated). Tested on latest Chrome 110.0.5481.77

The reason is that, although the underlying iframe gets created once Printd is instantiated BUT the whole content to be printed is always replaced in the iframe (emptied) once either `print` or `printURL` methods are called.

Maybe Printd should make it easier and add support for `beforeprint` and `afterprint` in its API directly.

**Comment by joseluisq** [comment]
Added two methods to ease printing events. See [v1.6.0](https://github.com/joseluisq/printd/releases/tag/v1.6.0)

**Comment by ApplY3D** [comment]
![Screenshot 2023-06-05 at 14 06 04](https://github.com/joseluisq/printd/assets/63294836/351292ed-58e2-4875-a50a-bcf45de3e12f)
in Firefox both events fires before print. Tested on https://codepen.io/joseluisq/pen/VzRpGb
