### ISSUE TITLE
Should use `css object style` like `SCSS` instead of `CSS Text` or not?

### ISSUE THREAD

**Issue by thearabbit** [joseluisq/printd#5]
I think that It is easy if we use `css object style` like `scss` instead of `css text`.
What do you think?

**Comment by joseluisq** [comment]
> I think that It is easy if we use css object style like scss instead of css text.
> What do you think?

You can use css object and parse it to plain css text #2. 

Basically, I prefer to let object styles as optional on developer side. 
As you can see [#L51](https://github.com/joseluisq/printd/blob/master/src/index.ts#L51) the styles are appended to `head` tag (globally).

Since `Printd` clone your element (using [cloneNode](https://github.com/joseluisq/printd/blob/master/src/index.ts#L45)). It means that your element styles are available when you invoke `d.print(el)` (not css classes). 
Otherwise you can apply before specific styles directly to your element.

For example:

```ts
const el: HTMLElement = document.getElementById('app')
// here you can customize the way how you can append styles
el.style.setProperty('font-family', 'sans-serif')
el.style.setProperty('color', '#c7254e')

// `font-family` and `color` styles will be available
const d: Printd = new Printd()
d.print(el)
 ```

Maybe in the future it could consider object styles, but now I recommend to parsing your objects to plain css text.
